import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
// import { Vazirmatn } from 'next/font/google'
// const vazirmatn = Vazirmatn({ subsets: ['latin'] })
const vazir = localFont({
  src: [
    {
      path: "webfonts/Vazirmatn-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "webfonts/Vazirmatn-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-vazirmatn",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${geistSans.variable} ${vazir.variable} antialiased`}>
        <h1>کمال حبیبی</h1>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
